---
title: "Chicage Temperatures"
author: "John Yuill"
date: "December 27, 2015"
output: html_document
---

Charts showing monthly temperatures for Chicago, in **Celsius** based on:

* monthly average
* minimum temperature recorded for each month
* maximum temperature recorderd for each month.

```{r, echo=FALSE}
library(ggplot2)

```


### Data setup
Data from:
[Roger Peng's Github repository for online Data Science courses](https://github.com/DataScienceSpecialization/courses/tree/master/03_GettingData/dplyr)

```{r, echo=FALSE}
chicagomthlytemp <- read.csv("chicagomthlytemp.csv")
chicagotempcelsius <- read.csv("chicagotempcelsius.csv")
chicagotempcelsius$month <- as.factor(chicagotempcelsius$month)

```

### Monthly Temperature Distribution: Lows, Highs, Averages
```{r, echo=FALSE}
qplot(month,tempc,data=chicagotempcelsius,geom="boxplot")+ theme_classic(base_size=16) +
  xlab("Month of Year") +
  ylab("Temperature Range During Month") +
  geom_hline(yintercept=0, linetype=2) +
  scale_y_continuous(limits=c(-30,35),breaks=seq(-30,30,10)) +
  scale_x_discrete(breaks=seq(1,12,1))

```


### Average Monthly Temperature
```{r, echo=FALSE}
ggplot(data=chicagomthlytemp,aes(x=month,y=avetempc)) + geom_bar(stat="identity") + 
  theme_classic(base_size=16) +
  scale_x_discrete(breaks=c(seq(1,12,1))) +
  xlab("Month of Year") +
  ylab("Ave Temp for Month")

```


### Minimum Monthly Temperature
```{r, echo=FALSE}
ggplot(data=chicagomthlytemp,aes(x=month,y=mintempc)) + geom_bar(stat="identity") + 
  theme_classic(base_size=16) +
  scale_x_discrete(breaks=c(seq(1,12,1))) +
  xlab("Month of Year") +
  ylab("Minimum Temp for Month")


```


### Maximum Monthly Temperature
```{r, echo=FALSE}

ggplot(data=chicagomthlytemp,aes(x=month,y=maxtempc)) + geom_bar(stat="identity") + 
  theme_classic(base_size=16) +
  scale_x_discrete(breaks=c(seq(1,12,1))) +
  xlab("Month of Year") +
  ylab("Maximum Temp for Month")

```


